#!/usr/bin/env python3
"""
scripts/runtime/normalize_runtime_findings.py

Parses raw Prowler 5 JSON-OCSF output, normalizes findings, deduplicates,
and generates the runtime findings summary.
Attributes findings exclusively based on the tag-filtered scan scope.

Usage:
    python scripts/runtime/normalize_runtime_findings.py <SCAN_ID>
"""

import sys
import json
from pathlib import Path
from collections import defaultdict

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT_DIR))

from scripts.utils.evidence import (
    safe_read_json,
    safe_write_json,
    utc_now_iso
)

def _normalize_severity(orig: str) -> str:
    orig = str(orig).upper()
    if orig in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"):
        return orig
    if orig == "INFO":
        return "INFORMATIONAL"
    return "UNKNOWN"

def get_check_status(finding: dict) -> str:
    return str(
        finding.get("status_code")
        or finding.get("check_status")
        or finding.get("Status")
        or ""
    ).strip().upper()

def _find_prowler_ocsf(raw_dir: Path) -> Path | None:
    files = list(raw_dir.glob("*.ocsf.json")) + list(raw_dir.glob("*.json"))
    if not files:
        return None
    return sorted(files, key=lambda f: f.stat().st_mtime)[-1]

def parse_ocsf(file_path: Path) -> list[dict]:
    findings = []
    try:
        content = file_path.read_text().strip()
        if content.startswith("["):
            findings = json.loads(content)
        else:
            for line in content.splitlines():
                line = line.strip()
                if line:
                    findings.append(json.loads(line))
    except Exception as e:
        print(f"[normalize] ERROR: Failed to parse OCSF JSON: {e}")
    return findings

def normalize_prowler(scan_id: str) -> None:
    runtime_dir = ROOT_DIR / "reports" / "runtime" / scan_id
    prowler_raw_dir = runtime_dir / "prowler" / "raw"
    normalized_dir = runtime_dir / "normalized"
    normalized_dir.mkdir(parents=True, exist_ok=True)
    
    findings_out_path = normalized_dir / "runtime-findings.json"
    summary_out_path = normalized_dir / "runtime-findings-summary.json"

    registry_path = ROOT_DIR / "mappings" / "runtime" / "prowler-security-hub-standards.json"
    registry = safe_read_json(str(registry_path)) or {"checks": {}}
    registry_checks = registry.get("checks", {})
    
    ocsf_path = _find_prowler_ocsf(prowler_raw_dir)
    
    if not ocsf_path:
        print("[normalize] ERROR: No Prowler JSON output found.")
        op_error = {
            "scan_id": scan_id,
            "classification": "OPERATIONAL_ERROR",
            "code": "PROWLER_EXECUTION_FAILED",
            "message": "No JSON-OCSF output generated by Prowler.",
            "security_conclusion_available": False
        }
        safe_write_json(str(normalized_dir / "runtime-operational-error.json"), op_error)
        sys.exit(1)

    raw_findings = parse_ocsf(ocsf_path)
    if not raw_findings:
        print("[normalize] No findings parsed from OCSF.")
    
    # Identify failures
    failed_findings = []
    for f in raw_findings:
        if get_check_status(f) == "FAIL":
            failed_findings.append(f)

    # Deduplication map
    dedup_map = defaultdict(list)
    
    for f in failed_findings:
        finding_info = f.get("finding_info", {})
        metadata = f.get("metadata", {})
        
        check_id = metadata.get("event_code") or finding_info.get("analytic", {}).get("uid") or f.get("type_uid") or f.get("CheckID") or "unknown"
        
        resources = f.get("resources", [])
        if not resources:
            resources = [{"uid": f.get("ResourceId", "unknown"), "cloud_partition": f.get("ResourceArn", ""), "region": f.get("Region", "unknown")}]
            
        r_uid = resources[0].get("uid", "unknown")
        if str(r_uid).startswith("arn:"):
            r_arn = r_uid
            r_id = r_uid.split(":")[-1] if ":" in r_uid else r_uid
        else:
            r_arn = resources[0].get("cloud_partition") or f.get("ResourceArn", "")
            r_id = r_uid

        account = f.get("cloud", {}).get("account", {}).get("uid", f.get("AccountId", "unknown"))
        region = resources[0].get("region", f.get("Region", "unknown"))
        
        dedup_key = f"{account}|{region}|{r_id}|{check_id}"
        dedup_map[dedup_key].append(f)

    unique_findings_count = len(dedup_map)
    total_merged = len(failed_findings) - unique_findings_count
    
    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFORMATIONAL": 0, "UNKNOWN": 0}
    deployment_findings = []

    for dedup_key, finding_group in dedup_map.items():
        # Use first for core metadata
        f = finding_group[0]
        finding_info = f.get("finding_info", {})
        metadata = f.get("metadata", {})
        
        check_id = metadata.get("event_code") or finding_info.get("analytic", {}).get("uid") or f.get("type_uid") or f.get("CheckID") or "unknown"
        reg_info = registry_checks.get(check_id, {})
        canonical_control = reg_info.get("canonical_control", check_id.upper())
        
        resources = f.get("resources", [])
        if not resources:
            resources = [{"uid": f.get("ResourceId", "unknown"), "cloud_partition": f.get("ResourceArn", ""), "region": f.get("Region", "unknown"), "name": f.get("ResourceName", ""), "group": {"name": "unknown"}}]
            
        r_uid = resources[0].get("uid", "unknown")
        if str(r_uid).startswith("arn:"):
            r_arn = r_uid
            r_id = r_uid.split(":")[-1] if ":" in r_uid else r_uid
        else:
            r_arn = resources[0].get("cloud_partition") or f.get("ResourceArn", "")
            r_id = r_uid
            
        r_name = resources[0].get("name") or f.get("ResourceName", "")
        service = resources[0].get("group", {}).get("name") or finding_info.get("analytic", {}).get("category") or "unknown"
        account = f.get("cloud", {}).get("account", {}).get("uid", f.get("AccountId", "unknown"))
        region = resources[0].get("region", f.get("Region", "unknown"))
        
        # Severity
        prowler_sev = str(f.get("severity", f.get("Severity", "UNKNOWN"))).upper()
        if not prowler_sev or prowler_sev == "UNKNOWN":
            prowler_sev = str(finding_info.get("severity", "UNKNOWN")).upper()
            
        override_sev = reg_info.get("severity_override")
        if override_sev:
            norm_sev = _normalize_severity(override_sev)
            sev_source = "LOCAL_REVIEWED_OVERRIDE"
        else:
            norm_sev = _normalize_severity(prowler_sev)
            sev_source = "PROWLER_METADATA"

        # Compliance
        standards = []
        compliance_data = f.get("unmapped", {}).get("compliance") or f.get("compliance") or f.get("Compliance", {})
        if isinstance(compliance_data, dict):
            for framework, versions in compliance_data.items():
                if isinstance(versions, dict):
                    for version, controls in versions.items():
                        if isinstance(controls, list):
                            for control in controls:
                                standards.append({
                                    "framework": framework,
                                    "version": str(version),
                                    "control_id": str(control),
                                    "source": "PROWLER_COMPLIANCE_METADATA"
                                })
        elif isinstance(compliance_data, list):
            for entry in compliance_data:
                if isinstance(entry, dict):
                    standards.append({
                        "framework": entry.get("Framework", entry.get("framework", "unknown")),
                        "version": entry.get("Version", entry.get("version", "unknown")),
                        "control_id": entry.get("Requirement", entry.get("Control", entry.get("control", "unknown"))),
                        "source": "PROWLER_COMPLIANCE_METADATA"
                    })

        # Since it was discovered via the resource tag filter, it belongs to the deployment
        normalized = {
            "finding_id": f"PRW-{canonical_control}-{r_id}",
            "scanner": "prowler",
            "control_id": canonical_control,
            "title": f.get("title") or finding_info.get("title") or f.get("CheckTitle", check_id),
            "description": f.get("message") or finding_info.get("desc") or f.get("Description", ""),
            "severity": {
                "original": prowler_sev,
                "normalized": norm_sev,
                "source": sev_source
            },
            "compliance": standards,
            "resource": {
                "id": r_id,
                "arn": r_arn,
                "name": r_name,
                "aws_account_id": account,
                "aws_region": region,
                "tags": f.get("cloud", {}).get("account", {}).get("tags", {})
            },
            "classification": "DEPLOYMENT_FINDING",
            "attribution": {
                "method": "PROWLER_RESOURCE_TAG_FILTER",
                "scan_id": scan_id,
                "confidence": "HIGH"
            },
            "status": "FAIL",
            "remediation": {
                "text": f.get("remediation", {}).get("desc", f.get("Remediation", {}).get("Recommendation", {}).get("Text", "")),
                "references": f.get("remediation", {}).get("references", [f.get("Remediation", {}).get("Recommendation", {}).get("Url", "")])
            },
            "duplicate_metadata": {
                "merged_records": len(finding_group),
                "source_record_ids": []
            },
            "first_observed_at": utc_now_iso(),
            "generated_at": utc_now_iso()
        }
        
        deployment_findings.append(normalized)
        severity_counts[norm_sev] += 1
        
    out_data = {
        "schema_version": "2.0",
        "scan_id": scan_id,
        "scanner": {
            "name": "prowler",
            "version": "5.28.1"
        },
        "scan_scope": {
            "type": "TAGGED_DEPLOYMENT_RESOURCES_ONLY",
            "resource_tags": {
                "scan-id": scan_id,
                "managed-by": "iac-security-framework"
            }
        },
        "summary": {
            "raw_findings": len(failed_findings),
            "deduplicated_findings": unique_findings_count,
            "merged_duplicate_records": total_merged,
            "critical": severity_counts.get("CRITICAL", 0),
            "high": severity_counts.get("HIGH", 0),
            "medium": severity_counts.get("MEDIUM", 0),
            "low": severity_counts.get("LOW", 0),
            "informational": severity_counts.get("INFORMATIONAL", 0),
            "unknown": severity_counts.get("UNKNOWN", 0)
        },
        "findings": deployment_findings
    }
    
    safe_write_json(str(findings_out_path), out_data)

    summary_out = {
        "scan_id": scan_id,
        "status": "SUCCESS_WITH_FINDINGS" if unique_findings_count > 0 else "SUCCESS_NO_FINDINGS",
        "total_findings": unique_findings_count,
        "severity_counts": severity_counts,
        "findings": [
            {
                "check_id": f["control_id"],
                "title": f["title"],
                "severity": f["severity"]["normalized"],
                "service": service,
                "resource_id": f["resource"]["id"],
                "resource_arn": f["resource"]["arn"],
                "region": f["resource"]["aws_region"]
            }
            for f in deployment_findings
        ]
    }
    safe_write_json(str(summary_out_path), summary_out)
    
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: normalize_runtime_findings.py <SCAN_ID>")
        sys.exit(1)
    normalize_prowler(sys.argv[1])
