#!/usr/bin/env python3
"""
scripts/deployment/validate_plan_tags.py

Reads a Terraform plan JSON file and verifies that every taggable AWS
resource change carries the required scan-id and managed-by tags.

Tags are injected by the framework through AWS Provider environment variables:
    TF_AWS_DEFAULT_TAGS_scan-id=<SCAN_ID>
    TF_AWS_DEFAULT_TAGS_managed-by=iac-security-framework

The plan validator is the final authority before deployment eligibility:
  - The current SCAN_ID is known before planning.  It MUST appear as a
    concrete value in tags_all (not as "known after apply").
  - Unknown / computed tag values are treated as failures.
  - If a resource-level tag overrides the provider default, it must still
    equal the expected value.

Usage:
    python scripts/deployment/validate_plan_tags.py <SCAN_ID> <PLAN_JSON_PATH>

Inputs:
    SCAN_ID         — The current scan identifier.
    PLAN_JSON_PATH  — Path to terraform-plan.json generated by
                      `terraform show -json tfplan`.

Output:
    reports/deployment/<SCAN_ID>/tag-validation.json
"""

import argparse
import json
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT_DIR))
from scripts.utils.evidence import safe_write_json, utc_now_iso

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REQUIRED_MANAGED_BY = "iac-security-framework"
INJECTION_MODE = "aws_provider_environment_variables"

# Actions that need tag checking (resource being created or updated)
TAGGABLE_ACTIONS = {"create", "update", "create-delete", "delete-create"}

# Actions to skip
SKIP_ACTIONS = {"delete", "no-op"}


# ---------------------------------------------------------------------------
# Core validation logic
# ---------------------------------------------------------------------------

def validate_tags(plan_data: dict, scan_id: str) -> dict:
    """
    Examine resource_changes and strictly validate required tags.

    Key rules:
    - scan-id must be the current SCAN_ID as a concrete string.
    - managed-by must be exactly "iac-security-framework".
    - "known after apply" / boolean-true values for tag keys are FAILURES.
    - Resource-level tags that override provider defaults are detected.
    """
    resource_changes = plan_data.get("resource_changes", [])

    taggable_checked: list[dict] = []
    resources_passed: list[str] = []
    resources_failed: list[dict] = []
    untaggable: list[dict] = []
    skipped_actions: list[dict] = []
    resources_unknown: list[dict] = []

    for rc in resource_changes:
        address = rc.get("address", "unknown")
        resource_type = rc.get("type", "unknown")
        change = rc.get("change", {})
        actions = set(change.get("actions", []))

        # ---- Skip delete-only and no-op ----
        if actions <= SKIP_ACTIONS:
            skipped_actions.append({
                "resource": address,
                "type": resource_type,
                "actions": sorted(actions),
                "reason": "delete_or_noop",
            })
            continue

        # ---- Only process taggable actions ----
        if not actions & TAGGABLE_ACTIONS:
            skipped_actions.append({
                "resource": address,
                "type": resource_type,
                "actions": sorted(actions),
                "reason": "non_taggable_action",
            })
            continue

        after = change.get("after") or {}
        after_unknown = change.get("after_unknown") or {}

        # ---- Determine if resource supports tagging ----
        has_tags_key = (
            "tags" in after
            or "tags_all" in after
            or "tags" in after_unknown
            or "tags_all" in after_unknown
        )

        if not has_tags_key:
            untaggable.append({
                "resource": address,
                "type": resource_type,
                "reason": "no_tags_or_tags_all_key",
            })
            continue

        # ---- Resolve effective tags ----
        # Prefer tags_all (merges resource-level tags + provider default_tags)
        tags_all_raw = after.get("tags_all")
        tags_raw = after.get("tags")
        tags_all_unknown = after_unknown.get("tags_all", {})
        tags_unknown = after_unknown.get("tags", {})

        tags_all: dict | None = tags_all_raw if isinstance(tags_all_raw, dict) else None
        tags: dict | None = tags_raw if isinstance(tags_raw, dict) else None

        # Use tags_all preferentially; fall back to tags
        effective_tags: dict = {}
        if tags_all:
            effective_tags = tags_all
        elif tags:
            effective_tags = tags

        entry = {
            "resource": address,
            "type": resource_type,
            "actions": sorted(actions),
        }
        taggable_checked.append(entry)

        missing_tags: list[str] = []
        incorrect_tags: list[dict] = []
        unknown_values: list[dict] = []

        # ---- Validate scan-id ----
        # Check if it's in the unknown map (known-after-apply) — FAIL
        scan_id_unknown = (
            (isinstance(tags_all_unknown, dict) and tags_all_unknown.get("scan-id"))
            or (isinstance(tags_unknown, dict) and tags_unknown.get("scan-id"))
        )
        scan_id_value = effective_tags.get("scan-id")

        if scan_id_unknown and scan_id_value is None:
            # scan-id will only be known after apply — this is a FAIL
            # because we know the SCAN_ID before planning
            unknown_values.append({
                "tag": "scan-id",
                "reason": "KNOWN_AFTER_APPLY",
                "expected": scan_id,
            })
        elif scan_id_value is None:
            missing_tags.append("scan-id")
        elif not isinstance(scan_id_value, str):
            # Boolean True or non-string  — treat as unknown/not-set
            unknown_values.append({
                "tag": "scan-id",
                "reason": "NON_STRING_VALUE",
                "actual": repr(scan_id_value),
                "expected": scan_id,
            })
        elif scan_id_value != scan_id:
            # Value present but wrong — may indicate resource-level override
            reason = (
                "RESOURCE_TAG_OVERRIDES_FRAMEWORK_DEFAULT"
                if scan_id_value
                else "INCORRECT_VALUE"
            )
            incorrect_tags.append({
                "tag": "scan-id",
                "expected": scan_id,
                "actual": scan_id_value,
                "reason": reason,
            })

        # ---- Validate managed-by ----
        managed_by_unknown = (
            (isinstance(tags_all_unknown, dict) and tags_all_unknown.get("managed-by"))
            or (isinstance(tags_unknown, dict) and tags_unknown.get("managed-by"))
        )
        managed_by_value = effective_tags.get("managed-by")

        if managed_by_unknown and managed_by_value is None:
            unknown_values.append({
                "tag": "managed-by",
                "reason": "KNOWN_AFTER_APPLY",
                "expected": REQUIRED_MANAGED_BY,
            })
        elif managed_by_value is None:
            missing_tags.append("managed-by")
        elif not isinstance(managed_by_value, str):
            unknown_values.append({
                "tag": "managed-by",
                "reason": "NON_STRING_VALUE",
                "actual": repr(managed_by_value),
                "expected": REQUIRED_MANAGED_BY,
            })
        elif managed_by_value != REQUIRED_MANAGED_BY:
            reason = (
                "RESOURCE_TAG_OVERRIDES_FRAMEWORK_DEFAULT"
                if managed_by_value
                else "INCORRECT_VALUE"
            )
            incorrect_tags.append({
                "tag": "managed-by",
                "expected": REQUIRED_MANAGED_BY,
                "actual": managed_by_value,
                "reason": reason,
            })

        # ---- Classify result ----
        if missing_tags or incorrect_tags or unknown_values:
            failure_entry = {
                **entry,
                "missing_tags": missing_tags,
                "incorrect_tags": incorrect_tags,
                "unknown_values": unknown_values,
            }
            if incorrect_tags and any(
                it.get("reason") == "RESOURCE_TAG_OVERRIDES_FRAMEWORK_DEFAULT"
                for it in incorrect_tags
            ):
                failure_entry["reason"] = "RESOURCE_TAG_OVERRIDES_FRAMEWORK_DEFAULT"

            if unknown_values:
                resources_unknown.append(failure_entry)
            resources_failed.append(failure_entry)
        else:
            resources_passed.append(address)

    status = "PASS" if len(resources_failed) == 0 else "FAIL"

    return {
        "schema_version": "1.0",
        "scan_id": scan_id,
        "generated_at_utc": utc_now_iso(),
        "status": status,
        "injection_mode": INJECTION_MODE,
        "required_tags": {
            "scan-id": scan_id,
            "managed-by": REQUIRED_MANAGED_BY,
        },
        "taggable_resources_checked": len(taggable_checked),
        "resources_passed": len(resources_passed),
        "resources_failed": len(resources_failed),
        "resources_unknown": len(resources_unknown),
        "untaggable_or_not_applicable": untaggable,
        "skipped_actions": skipped_actions,
        "failures": resources_failed,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate SCAN_ID and managed-by tags in a Terraform plan."
    )
    parser.add_argument("scan_id", help="The current SCAN_ID")
    parser.add_argument("plan_json", help="Path to terraform-plan.json")
    args = parser.parse_args()

    scan_id: str = args.scan_id
    plan_json_path = Path(args.plan_json)

    deploy_dir = ROOT_DIR / "reports" / "deployment" / scan_id
    deploy_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Load plan JSON                                                      #
    # ------------------------------------------------------------------ #
    if not plan_json_path.is_file():
        error = {
            "schema_version": "1.0",
            "scan_id": scan_id,
            "generated_at_utc": utc_now_iso(),
            "status": "ERROR",
            "error": f"Plan JSON not found at {plan_json_path}",
        }
        safe_write_json(str(deploy_dir / "tag-validation.json"), error)
        print(f"[validate_plan_tags] ERROR: {plan_json_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        plan_data = json.loads(plan_json_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        error = {
            "schema_version": "1.0",
            "scan_id": scan_id,
            "generated_at_utc": utc_now_iso(),
            "status": "ERROR",
            "error": f"Failed to parse plan JSON: {exc}",
        }
        safe_write_json(str(deploy_dir / "tag-validation.json"), error)
        print(f"[validate_plan_tags] ERROR: Failed to parse {plan_json_path}", file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------ #
    # Validate tags                                                       #
    # ------------------------------------------------------------------ #
    result = validate_tags(plan_data, scan_id)
    safe_write_json(str(deploy_dir / "tag-validation.json"), result)

    # ------------------------------------------------------------------ #
    # Console output                                                      #
    # ------------------------------------------------------------------ #
    print(f"\n{'='*60}")
    print(f"  SCAN_ID TAG VALIDATION — {result['status']}")
    print(f"{'='*60}")
    print(f"  SCAN_ID              : {scan_id}")
    print(f"  Injection Mode       : {INJECTION_MODE}")
    print(f"  Taggable Checked     : {result['taggable_resources_checked']}")
    print(f"  Passed               : {result['resources_passed']}")
    print(f"  Failed               : {result['resources_failed']}")
    print(f"  Unknown Values       : {result['resources_unknown']}")
    print(f"  Untaggable/N/A       : {len(result['untaggable_or_not_applicable'])}")
    print(f"  Skipped (del/noop)   : {len(result['skipped_actions'])}")

    if result["failures"]:
        print(f"\n{'-'*60}")
        print(f"  FAILURES")
        print(f"{'-'*60}")
        for f in result["failures"]:
            print(f"  {f['resource']}")
            if f.get("missing_tags"):
                print(f"    Missing tags      : {', '.join(f['missing_tags'])}")
            if f.get("incorrect_tags"):
                for it in f["incorrect_tags"]:
                    print(
                        f"    Incorrect [{it['tag']}]: "
                        f"expected={it['expected']} actual={it['actual']} "
                        f"reason={it.get('reason', '')}"
                    )
            if f.get("unknown_values"):
                for uv in f["unknown_values"]:
                    print(
                        f"    Unknown [{uv['tag']}]  : "
                        f"reason={uv['reason']} expected={uv['expected']}"
                    )

    print(f"\n{'='*60}\n")

    if result["status"] != "PASS":
        sys.exit(1)


if __name__ == "__main__":
    main()
