#!/usr/bin/env python3
"""
scripts/deployment/validate_plan_tags.py

Reads a Terraform plan JSON file and verifies that every taggable AWS
resource change carries the required scan-id and managed-by tags.

Usage:
    python scripts/deployment/validate_plan_tags.py <SCAN_ID> <PLAN_JSON_PATH>

Inputs:
    SCAN_ID         — The current scan identifier.
    PLAN_JSON_PATH  — Path to the terraform-plan.json generated by
                      `terraform show -json tfplan`.

Output:
    reports/deployment/<SCAN_ID>/tag-validation.json
"""

import argparse
import json
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT_DIR))
from scripts.utils.evidence import safe_write_json, utc_now_iso


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REQUIRED_TAGS = {
    "scan-id": None,       # value checked dynamically against SCAN_ID
    "managed-by": "iac-security-framework",
}

# Actions that require tag checking (resources being created or updated)
TAGGABLE_ACTIONS = {"create", "update", "create-delete", "delete-create"}

# Actions to skip entirely
SKIP_ACTIONS = {"delete", "no-op"}


# ---------------------------------------------------------------------------
# Core validation logic
# ---------------------------------------------------------------------------

def validate_tags(
    plan_data: dict,
    scan_id: str,
) -> dict:
    """Examine resource_changes and validate required tags.

    Returns a structured result dict suitable for JSON serialisation.
    """
    resource_changes = plan_data.get("resource_changes", [])

    resources_checked: list[dict] = []
    resources_passed: list[dict] = []
    resources_failed: list[dict] = []
    untaggable: list[dict] = []
    skipped_actions: list[dict] = []

    for rc in resource_changes:
        address = rc.get("address", "unknown")
        resource_type = rc.get("type", "unknown")
        change = rc.get("change", {})
        actions = set(change.get("actions", []))

        # Skip delete-only and no-op resources
        if actions <= SKIP_ACTIONS:
            skipped_actions.append({
                "resource": address,
                "type": resource_type,
                "actions": sorted(actions),
                "reason": "delete_or_noop",
            })
            continue

        # Check if any action is taggable
        if not actions & TAGGABLE_ACTIONS:
            skipped_actions.append({
                "resource": address,
                "type": resource_type,
                "actions": sorted(actions),
                "reason": "non_taggable_action",
            })
            continue

        # Extract tag values from the plan
        after = change.get("after") or {}
        after_unknown = change.get("after_unknown") or {}

        # tags_all is the merged result of tags + default_tags
        tags = after.get("tags") if isinstance(after.get("tags"), dict) else None
        tags_all = after.get("tags_all") if isinstance(after.get("tags_all"), dict) else None

        # Check if resource has any tag-related key at all
        has_tags_key = (
            "tags" in after
            or "tags_all" in after
            or "tags" in after_unknown
            or "tags_all" in after_unknown
        )

        if not has_tags_key:
            # Resource type does not support tagging
            untaggable.append({
                "resource": address,
                "type": resource_type,
                "reason": "no_tags_or_tags_all_key",
            })
            continue

        # Resource is taggable — check for required tags
        # Prefer tags_all (includes default_tags), fall back to tags
        effective_tags = {}
        if tags_all:
            effective_tags = tags_all
        elif tags:
            effective_tags = tags

        missing_tags: list[str] = []
        incorrect_tags: list[dict] = []

        # Check scan-id
        scan_id_value = effective_tags.get("scan-id")
        if scan_id_value is None:
            # Check if it's in after_unknown (known after apply)
            unknown_tags = after_unknown.get("tags_all", {}) or after_unknown.get("tags", {})
            if isinstance(unknown_tags, dict) and unknown_tags.get("scan-id"):
                pass  # Will be set at apply time; accept as pending
            else:
                missing_tags.append("scan-id")
        elif scan_id_value != scan_id:
            incorrect_tags.append({
                "tag": "scan-id",
                "expected": scan_id,
                "actual": scan_id_value,
            })

        # Check managed-by
        managed_by_value = effective_tags.get("managed-by")
        if managed_by_value is None:
            unknown_tags = after_unknown.get("tags_all", {}) or after_unknown.get("tags", {})
            if isinstance(unknown_tags, dict) and unknown_tags.get("managed-by"):
                pass
            else:
                missing_tags.append("managed-by")
        elif managed_by_value != REQUIRED_TAGS["managed-by"]:
            incorrect_tags.append({
                "tag": "managed-by",
                "expected": REQUIRED_TAGS["managed-by"],
                "actual": managed_by_value,
            })

        entry = {
            "resource": address,
            "type": resource_type,
            "actions": sorted(actions),
        }

        resources_checked.append(entry)

        if missing_tags or incorrect_tags:
            failure_entry = {**entry, "missing_tags": missing_tags, "incorrect_tags": incorrect_tags}
            resources_failed.append(failure_entry)
        else:
            resources_passed.append(entry)

    status = "PASS" if len(resources_failed) == 0 else "FAIL"

    return {
        "scan_id": scan_id,
        "generated_at": utc_now_iso(),
        "status": status,
        "required_tags": {
            "scan-id": scan_id,
            "managed-by": "iac-security-framework",
        },
        "taggable_resources_checked": len(resources_checked),
        "resources_passed": len(resources_passed),
        "resources_failed": len(resources_failed),
        "untaggable_or_not_applicable": untaggable,
        "skipped_actions": skipped_actions,
        "failures": resources_failed,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate SCAN_ID and managed-by tags in a Terraform plan."
    )
    parser.add_argument("scan_id", help="The current SCAN_ID")
    parser.add_argument("plan_json", help="Path to terraform-plan.json")
    args = parser.parse_args()

    scan_id: str = args.scan_id
    plan_json_path = Path(args.plan_json)

    deploy_dir = ROOT_DIR / "reports" / "deployment" / scan_id
    deploy_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Load plan JSON                                                      #
    # ------------------------------------------------------------------ #
    if not plan_json_path.is_file():
        error = {
            "scan_id": scan_id,
            "generated_at": utc_now_iso(),
            "status": "ERROR",
            "error": f"Plan JSON not found at {plan_json_path}",
        }
        safe_write_json(str(deploy_dir / "tag-validation.json"), error)
        print(f"[validate_plan_tags] ERROR: {plan_json_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        plan_data = json.loads(plan_json_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        error = {
            "scan_id": scan_id,
            "generated_at": utc_now_iso(),
            "status": "ERROR",
            "error": f"Failed to parse plan JSON: {exc}",
        }
        safe_write_json(str(deploy_dir / "tag-validation.json"), error)
        print(f"[validate_plan_tags] ERROR: Failed to parse {plan_json_path}", file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------ #
    # Validate tags                                                       #
    # ------------------------------------------------------------------ #
    result = validate_tags(plan_data, scan_id)

    safe_write_json(str(deploy_dir / "tag-validation.json"), result)

    # ------------------------------------------------------------------ #
    # Console output                                                      #
    # ------------------------------------------------------------------ #
    print(f"\n{'='*60}")
    print(f"  SCAN_ID TAG VALIDATION")
    print(f"{'='*60}")
    print(f"  SCAN_ID              : {scan_id}")
    print(f"  Status               : {result['status']}")
    print(f"  Taggable Checked     : {result['taggable_resources_checked']}")
    print(f"  Passed               : {result['resources_passed']}")
    print(f"  Failed               : {result['resources_failed']}")
    print(f"  Untaggable/N/A       : {len(result['untaggable_or_not_applicable'])}")
    print(f"  Skipped (del/noop)   : {len(result['skipped_actions'])}")

    if result["failures"]:
        print(f"\n{'-'*60}")
        print(f"  FAILURES")
        print(f"{'-'*60}")
        for f in result["failures"]:
            print(f"  {f['resource']}")
            if f.get("missing_tags"):
                print(f"    Missing tags: {', '.join(f['missing_tags'])}")
            if f.get("incorrect_tags"):
                for it in f["incorrect_tags"]:
                    print(f"    Incorrect: {it['tag']} expected={it['expected']} actual={it['actual']}")

    print(f"\n{'='*60}\n")

    if result["status"] != "PASS":
        sys.exit(1)


if __name__ == "__main__":
    main()
