#!/usr/bin/env python3
"""
scripts/deployment/validate_source_integrity.py

Computes a SHA256 manifest of all Terraform source files (.tf, .tf.json)
in the deployment root and compares it against a previously saved baseline.

Run BEFORE terraform plan:
    python scripts/deployment/validate_source_integrity.py <SCAN_ID> <TF_ROOT> --save

Run AFTER terraform plan to verify nothing changed:
    python scripts/deployment/validate_source_integrity.py <SCAN_ID> <TF_ROOT> --verify

Output:
    reports/deployment/<SCAN_ID>/deployment-source-integrity.json

The following Terraform-generated runtime files are excluded from the manifest:
    .terraform/
    .terraform.lock.hcl
    tfplan
    terraform.tfstate
    terraform.tfstate.backup
    crash.log
"""

import argparse
import hashlib
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT_DIR))
from scripts.utils.evidence import safe_read_json, safe_write_json, utc_now_iso

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# File patterns that are Terraform source (tracked)
SOURCE_SUFFIXES = {".tf", ".tf.json"}

# Directories to exclude (runtime-generated by terraform init)
EXCLUDE_DIRS = {".terraform"}

# Files to exclude (runtime-generated)
EXCLUDE_FILES = {
    ".terraform.lock.hcl",
    "tfplan",
    "terraform.tfstate",
    "terraform.tfstate.backup",
    "crash.log",
}

BASELINE_FILE = "deployment-source-baseline.json"
INTEGRITY_FILE = "deployment-source-integrity.json"


# ---------------------------------------------------------------------------
# Hashing
# ---------------------------------------------------------------------------

def sha256_bytes(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_manifest(tf_root: Path) -> dict[str, str]:
    """
    Return {relative_path: sha256} for all source-controlled Terraform files.

    Only includes files with SOURCE_SUFFIXES, excludes EXCLUDE_DIRS and
    EXCLUDE_FILES.  Paths are relative to tf_root for portability.
    """
    manifest: dict[str, str] = {}
    for path in sorted(tf_root.rglob("*")):
        if not path.is_file():
            continue
        # Skip excluded directories
        rel = path.relative_to(tf_root)
        parts = rel.parts
        if any(part in EXCLUDE_DIRS for part in parts):
            continue
        # Skip excluded files
        if path.name in EXCLUDE_FILES:
            continue
        # Only track source extensions
        if path.suffix not in SOURCE_SUFFIXES and not path.name.endswith(".tf.json"):
            continue
        try:
            manifest[str(rel)] = sha256_bytes(path)
        except OSError:
            manifest[str(rel)] = "READ_ERROR"
    return manifest


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Verify Terraform source file integrity before and after planning."
    )
    parser.add_argument("scan_id", help="Unique SCAN_ID")
    parser.add_argument("tf_root", help="Absolute path to Terraform deployment root")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--save",
        action="store_true",
        help="Compute and save the baseline manifest (run BEFORE terraform plan).",
    )
    group.add_argument(
        "--verify",
        action="store_true",
        help="Verify against baseline (run AFTER terraform plan).",
    )
    args = parser.parse_args()

    scan_id: str = args.scan_id
    tf_root = Path(args.tf_root)

    deploy_dir = ROOT_DIR / "reports" / "deployment" / scan_id
    deploy_dir.mkdir(parents=True, exist_ok=True)

    baseline_path = deploy_dir / BASELINE_FILE
    integrity_path = deploy_dir / INTEGRITY_FILE

    if not tf_root.is_dir():
        print(f"[source_integrity] ERROR: TF root not found: {tf_root}", file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------ #
    # --save: compute and persist baseline                                #
    # ------------------------------------------------------------------ #
    if args.save:
        manifest = compute_manifest(tf_root)
        baseline = {
            "scan_id": scan_id,
            "saved_at_utc": utc_now_iso(),
            "tf_root": str(tf_root),
            "files": manifest,
        }
        safe_write_json(str(baseline_path), baseline)
        print(f"[source_integrity] Baseline saved: {len(manifest)} source files")
        for rel, digest in manifest.items():
            print(f"  {rel}: {digest[:16]}...")
        return

    # ------------------------------------------------------------------ #
    # --verify: compare current state to baseline                         #
    # ------------------------------------------------------------------ #
    baseline_data = safe_read_json(str(baseline_path))
    if not isinstance(baseline_data, dict):
        print(
            f"[source_integrity] ERROR: Baseline not found at {baseline_path}. "
            "Run with --save before terraform plan.",
            file=sys.stderr,
        )
        sys.exit(1)

    baseline_manifest: dict[str, str] = baseline_data.get("files", {})
    current_manifest = compute_manifest(tf_root)

    changed_files: list[str] = []
    added_files: list[str] = []
    removed_files: list[str] = []

    # Changed or removed
    for rel, digest in baseline_manifest.items():
        if rel not in current_manifest:
            removed_files.append(rel)
        elif current_manifest[rel] != digest:
            changed_files.append(rel)

    # Added
    for rel in current_manifest:
        if rel not in baseline_manifest:
            added_files.append(rel)

    source_modified = bool(changed_files or added_files or removed_files)
    status = "FAIL" if source_modified else "PASS"

    result = {
        "schema_version": "1.0",
        "scan_id": scan_id,
        "generated_at_utc": utc_now_iso(),
        "status": status,
        "source_modified": source_modified,
        "files_checked": len(baseline_manifest),
        "changed_files": changed_files,
        "added_terraform_files": added_files,
        "removed_files": removed_files,
    }
    safe_write_json(str(integrity_path), result)

    print(f"\n{'='*60}")
    print(f"  SOURCE INTEGRITY — {status}")
    print(f"{'='*60}")
    print(f"  SCAN_ID          : {scan_id}")
    print(f"  Files Checked    : {len(baseline_manifest)}")
    print(f"  Source Modified  : {source_modified}")
    if changed_files:
        print(f"  Changed Files    :")
        for f in changed_files:
            print(f"    CHANGED  : {f}")
    if added_files:
        print(f"  Added Files      :")
        for f in added_files:
            print(f"    ADDED    : {f}")
    if removed_files:
        print(f"  Removed Files    :")
        for f in removed_files:
            print(f"    REMOVED  : {f}")
    print(f"{'='*60}\n")

    if source_modified:
        print(
            f"[source_integrity] FAIL: Terraform source files were modified. "
            "Framework policy prohibits modifying target .tf files.",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
